# Generated by Django 4.2 on 2023-07-03 15:12

from django.db import migrations


def populate_schools(apps, schema_editor):
    School = apps.get_model('base', 'School')
    schools = [
        'School of Applied Social Studies',
        'School of Computing',
        'School of Creative & Cultural Business',
        'School of Engineering',
        "Gray's School of Art",
        'School of Health Sciences',
        'School of Nursing, Midwifery & Paramedic Practice',
        'School of Pharmacy & Life Sciences',
        'Law School',
        'Scott Sutherland School of Architecture & Built Environment',
    ]
    for school_name in schools:
        School.objects.create(name=school_name)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_student_id'),
    ]

    operations = [
        migrations.RunPython(populate_schools),
    ]
