# Generated by Django 4.2 on 2023-06-28 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_comment_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscussionRoom',
            new_name='Room',
        ),
    ]
