# Generated by Django 4.2 on 2023-07-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='school',
        ),
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='base.school'),
        ),
    ]
