# Generated by Django 4.2 on 2023-07-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_room_school_room_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='school',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='base.school'),
        ),
    ]
