# Generated by Django 4.2 on 2023-07-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.png', upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
    ]
