# Generated by Django 4.2 on 2023-07-20 13:15

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='permit_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.png', upload_to=base.models.upload_to, verbose_name='Profile Picture'),
        ),
    ]
