# Generated by Django 4.2 on 2023-07-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_room_permit_all_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.png', upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
    ]
