# Generated by Django 4.2 on 2023-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_reportcategory_reportcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
