# Generated by Django 4.2 on 2023-07-31 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_populate_report_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcomment',
            old_name='details',
            new_name='description',
        ),
    ]
