# Generated by Django 4.2 on 2023-08-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
