# Generated by Django 4.2 on 2023-08-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_reportcomment_handled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
    ]
